name: Publish to NuGet

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: src
    - name: Pack
      run: dotnet pack -c Release -o ../nupkgs --no-build
      working-directory: src
    - name: Publish
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}  --skip-duplicate -s https://api.nuget.org/v3/index.json
